package Assign2;
import javafx.application.Application;
import javafx.geometry.HPos;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.VBox;
import javafx.scene.paint.Color;
import javafx.scene.shape.Line;
import javafx.scene.text.Font;
import javafx.stage.Stage;
public class Q1 extends Application {
    @Override
    public void start(Stage stage) {
        VBox pane = new VBox(5);
        pane.setPadding(new Insets(10,10,10,10));
        Label lblTitle=new Label("Registration/Login");
        Label lblSubTitle= new Label("Enter an email address and password");
        lblTitle.setFont(Font.font(25));
        pane.setAlignment(Pos.CENTER);
        pane.getChildren().addAll(lblTitle, lblSubTitle);
        GridPane gpTop= new GridPane();
        gpTop.setHgap(10);
        gpTop.setVgap(10);
        gpTop.setAlignment(Pos.CENTER);
        gpTop.setPadding(new Insets(5,10,10,10));
        Label lblEmail= new Label("Email to use:");
        gpTop.add(lblEmail, 0, 0);
        GridPane.setHalignment(lblEmail,HPos.RIGHT);
        TextField txtEmail= new TextField();
        gpTop.add(txtEmail, 1, 0);
        Label lblPassword= new Label("Enter a password:");
        gpTop.add(lblPassword,0, 1);
        GridPane.setHalignment(lblPassword,HPos.RIGHT);
        TextField txtPassword= new TextField();
        gpTop.add(txtPassword,1, 1);
        Label lblConfirm= new Label("Confirm your password:");
        gpTop.add(lblConfirm, 0, 2);
        GridPane.setHalignment(lblConfirm,HPos.RIGHT);
        TextField txtConfirm= new TextField();
        gpTop.add(txtConfirm, 1, 2);
        Button btnRegister = new Button("Register");
        gpTop.add(btnRegister, 1, 3);
        GridPane.setHalignment(btnRegister, HPos.RIGHT);
        pane.getChildren().addAll(gpTop);
        Line line = new Line(0,0,400,0);
        line.setStroke(Color.BLACK);
        line.setStrokeWidth(5);
        pane.getChildren().add(line);
        Label lblRegistered=new Label("Already Registered to the");
        Label lblRegistered2=new Label("Amazing COSC603 Program?");
        Label lblSubReg= new Label("Go ahead and login then");
        lblRegistered.setFont(Font.font(20));
        lblRegistered2.setFont(Font.font(20));
        lblRegistered.setStyle("-fx-alignment: CENTER");
        pane.setAlignment(Pos.CENTER);
        lblSubReg.setPadding(new Insets(0,0,10,0));
        pane.getChildren().addAll(lblRegistered, lblRegistered2,lblSubReg);
        GridPane gpBottom= new GridPane();
        gpBottom.setHgap(10);
        gpBottom.setVgap(10);
        gpBottom.setAlignment(Pos.CENTER);
        Label lblUserName= new Label("User name:");
        gpBottom.add(lblUserName,0, 0);
        GridPane.setHalignment(lblUserName,HPos.RIGHT);
        TextField txtUserName= new TextField();
        gpBottom.add(txtUserName, 1,0);
        Label lblPassword2= new Label("Password:");
        gpBottom.add(lblPassword2,0, 1);
        GridPane.setHalignment(lblPassword2,HPos.RIGHT);
        TextField txtPassword2= new TextField();
        gpBottom.add(txtPassword2,1, 1);
        Button btnLogin = new Button("Login");
        gpBottom.add(btnLogin,1,2);
        GridPane.setHalignment(btnLogin, HPos.RIGHT);
        pane.getChildren().addAll(gpBottom);
        Scene scene = new Scene(pane, 400, 425);
        stage.setScene(scene);
        stage.setTitle("The Amazing COSC603 Registration/Login");
        stage.show();
    }
}